"""empty message

Revision ID: 8a07bf2afc7f
Revises: 8b31dabc1afa
Create Date: 2020-05-18 21:09:27.369330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a07bf2afc7f'
down_revision = '8b31dabc1afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=24), nullable=True))
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
