"""empty message

Revision ID: 8b31dabc1afa
Revises: 735c0b43402e
Create Date: 2020-04-23 07:43:18.406410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b31dabc1afa'
down_revision = '735c0b43402e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym', 'status_description',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym', 'status_description',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
