"""empty message

Revision ID: 94d5cd283262
Revises: 8a07bf2afc7f
Create Date: 2020-05-18 21:21:20.274711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d5cd283262'
down_revision = '8a07bf2afc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
    # ### end Alembic commands ###
